name: MessengerSRV
version: '1.0-SNAPSHOT'
main: me.shinthl09.MessengerSRV
api-version: 1.13
author: ShinTHL09

commands:
  messengersrv:
    usage: /<command>
    description: "MessengerSRV Command"
    aliases: [ messenger ]
permissions:
  messengersrv.*:
    description: "Permissions Admin"
    default: op

